apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.api.nodePort }}